### ISSUE TITLE
"Managed" folder does not exist

### ISSUE THREAD

**Issue by ecentinela** [aBARICHELLO/far-lone-sails-noclip#2]
Hi! First of all, thank you for your work!

I'm trying to use it in order to learn a few things about the level design. Just downloaded the game from Steam and tried to locate the folder you specify in the readme "C:\Program Files (x86)\Steam\steamapps\common\FAR Lone Sails\Game\FarLoneSails_Data\Managed", but the "Managed" folder does not exist in my case and a I cannot find any "dll" with the name "Assembly-CSharp" in order to replace it.

Can you help me, please?

Thank you.

**Comment by abarichello** [comment]
Hi, this mod has been deprecated. It used to work on earlier versions of the game but I can't guarantee that it will work on current or future updates.
